# Generated by Django 2.1.7 on 2019-02-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='image/item')),
                ('describe', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
