# Generated by Django 2.1.7 on 2019-02-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0004_shopingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
